/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fa_3 (
    output reg s,
    output reg cout,
    input a,
    input b,
    input cin
  );
  
  
  
  always @* begin
    s = a ^ b ^ cin;
    cout = (a & b) + (a & cin) + (b & cin);
  end
endmodule
